#Configuración del Hotel \u2014 Hotel Sistema
#Sat May 23 21:24:22 CST 2026
hotel.slogan=Bienvenido a su hogar lejos del hogar
hotel.email=info@hotelvista.com.gt
hotel.nit=12345678-9
hotel.telefono=+502 45655347
hotel.nombre=Hotel Vista
hotel.direccion=6a Avenida 12-34, Zona 1, Ciudad de Guatemala
hotel.web=www.hotelvista.com.gt
hotel.iva=0.12
